// Code generated by go-swagger; DO NOT EDIT.

package store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrderByIDParams creates a new GetOrderByIDParams object
// with the default values initialized.
func NewGetOrderByIDParams() *GetOrderByIDParams {
	var ()
	return &GetOrderByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrderByIDParamsWithTimeout creates a new GetOrderByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrderByIDParamsWithTimeout(timeout time.Duration) *GetOrderByIDParams {
	var ()
	return &GetOrderByIDParams{

		timeout: timeout,
	}
}

// NewGetOrderByIDParamsWithContext creates a new GetOrderByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrderByIDParamsWithContext(ctx context.Context) *GetOrderByIDParams {
	var ()
	return &GetOrderByIDParams{

		Context: ctx,
	}
}

// NewGetOrderByIDParamsWithHTTPClient creates a new GetOrderByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrderByIDParamsWithHTTPClient(client *http.Client) *GetOrderByIDParams {
	var ()
	return &GetOrderByIDParams{
		HTTPClient: client,
	}
}

/*GetOrderByIDParams contains all the parameters to send to the API endpoint
for the get order by Id operation typically these are written to a http.Request
*/
type GetOrderByIDParams struct {

	/*OrderID
	  ID of pet that needs to be fetched

	*/
	OrderID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get order by Id params
func (o *GetOrderByIDParams) WithTimeout(timeout time.Duration) *GetOrderByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get order by Id params
func (o *GetOrderByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get order by Id params
func (o *GetOrderByIDParams) WithContext(ctx context.Context) *GetOrderByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get order by Id params
func (o *GetOrderByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get order by Id params
func (o *GetOrderByIDParams) WithHTTPClient(client *http.Client) *GetOrderByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get order by Id params
func (o *GetOrderByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderID adds the orderID to the get order by Id params
func (o *GetOrderByIDParams) WithOrderID(orderID int64) *GetOrderByIDParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the get order by Id params
func (o *GetOrderByIDParams) SetOrderID(orderID int64) {
	o.OrderID = orderID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrderByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param orderId
	if err := r.SetPathParam("orderId", swag.FormatInt64(o.OrderID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
