// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new user API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for user API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CreateUser(params *CreateUserParams) error

	CreateUsersWithArrayInput(params *CreateUsersWithArrayInputParams) error

	CreateUsersWithListInput(params *CreateUsersWithListInputParams) error

	DeleteUser(params *DeleteUserParams) error

	GetUserByName(params *GetUserByNameParams) (*GetUserByNameOK, error)

	LoginUser(params *LoginUserParams) (*LoginUserOK, error)

	LogoutUser(params *LogoutUserParams) error

	UpdateUser(params *UpdateUserParams) error

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateUser creates user

  This can only be done by the logged in user.
*/
func (a *Client) CreateUser(params *CreateUserParams) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateUserParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createUser",
		Method:             "POST",
		PathPattern:        "/user",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateUserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

/*
  CreateUsersWithArrayInput creates list of users with given input array
*/
func (a *Client) CreateUsersWithArrayInput(params *CreateUsersWithArrayInputParams) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateUsersWithArrayInputParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createUsersWithArrayInput",
		Method:             "POST",
		PathPattern:        "/user/createWithArray",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateUsersWithArrayInputReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

/*
  CreateUsersWithListInput creates list of users with given input array
*/
func (a *Client) CreateUsersWithListInput(params *CreateUsersWithListInputParams) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateUsersWithListInputParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createUsersWithListInput",
		Method:             "POST",
		PathPattern:        "/user/createWithList",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateUsersWithListInputReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

/*
  DeleteUser deletes user

  This can only be done by the logged in user.
*/
func (a *Client) DeleteUser(params *DeleteUserParams) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteUserParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteUser",
		Method:             "DELETE",
		PathPattern:        "/user/{username}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteUserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

/*
  GetUserByName gets user by user name
*/
func (a *Client) GetUserByName(params *GetUserByNameParams) (*GetUserByNameOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserByNameParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserByName",
		Method:             "GET",
		PathPattern:        "/user/{username}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetUserByNameReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetUserByNameOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getUserByName: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  LoginUser logs user into the system
*/
func (a *Client) LoginUser(params *LoginUserParams) (*LoginUserOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLoginUserParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "loginUser",
		Method:             "GET",
		PathPattern:        "/user/login",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &LoginUserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*LoginUserOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for loginUser: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  LogoutUser logs out current logged in user session
*/
func (a *Client) LogoutUser(params *LogoutUserParams) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLogoutUserParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "logoutUser",
		Method:             "GET",
		PathPattern:        "/user/logout",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &LogoutUserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

/*
  UpdateUser updateds user

  This can only be done by the logged in user.
*/
func (a *Client) UpdateUser(params *UpdateUserParams) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateUserParams()
	}

	_, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateUser",
		Method:             "PUT",
		PathPattern:        "/user/{username}",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdateUserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return err
	}
	return nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
